name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'

    - name: Install backend dependencies
      working-directory: ./backend/ThinkSync-backend-API
      run: npm install

    - name: Run backend tests
      working-directory: ./backend/ThinkSync-backend-API
      run: |
        echo "Running backend tests..."
        npm run test:coverage || true  # Allow the workflow to continue even if tests fail
      continue-on-error: true

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'

    - name: Create deployment package
      working-directory: ./backend/ThinkSync-backend-API
      run: |
        # Create a temporary directory for deployment
        mkdir -p deploy
        # Copy only necessary files
        cp -r src/ deploy/
        cp package.json deploy/
        cp package-lock.json deploy/
        cp .env deploy/
        # Install only production dependencies
        cd deploy
        npm ci --only=production
        cd ..

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thinksyncapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend/ThinkSync-backend-API/deploy'